// playground/svelte/src/App.svelte
<script lang="ts">
  import { adhesive } from "@adhesivejs/svelte";
  import svelteLogo from "./assets/svelte.svg";
  import viteLogo from "/vite.svg";

  let count: number = $state(0);
  const increment = () => {
    count += 1;
  };
</script>

<main>
  <div class="sticky-container">
    <div {@attach adhesive({ boundingEl: ".sticky-container" })}>
      Sticky Element
    </div>
    <a href="https://vite.dev" target="_blank" rel="noreferrer">
      <img src={viteLogo} class="logo" alt="Vite Logo" />
    </a>
    <a href="https://svelte.dev" target="_blank" rel="noreferrer">
      <img src={svelteLogo} class="logo svelte" alt="Svelte Logo" />
    </a>
  </div>
  <h1>Vite + Svelte</h1>

  <div class="card">
    <button onclick={increment}>
      count is {count}
    </button>
  </div>

  <p>
    Check out <a
      href="https://github.com/sveltejs/kit#readme"
      target="_blank"
      rel="noreferrer">SvelteKit</a
    >, the official Svelte app framework powered by Vite!
  </p>

  <p class="read-the-docs">Click on the Vite and Svelte logos to learn more</p>
</main>

<style>
  .logo {
    height: 6em;
    padding: 1.5em;
    will-change: filter;
    transition: filter 300ms;
  }
  .logo:hover {
    filter: drop-shadow(0 0 2em #646cffaa);
  }
  .logo.svelte:hover {
    filter: drop-shadow(0 0 2em #ff3e00aa);
  }
  .read-the-docs {
    color: #888;
  }
</style>

// playground/vue/src/App.vue
<script setup lang="ts">
import { AdhesiveContainer, useAdhesive } from "@adhesivejs/vue";
import { ref, useTemplateRef } from "vue";

const count = ref(0);

const targetEl = useTemplateRef("target");
const boundingEl = useTemplateRef("bounding");

useAdhesive({ target: targetEl, bounding: boundingEl });
</script>

<template>
  <div>
    <div ref="bounding">
      <div ref="target">Sticky Element</div>
      <a href="https://vite.dev" target="_blank" rel="noopener noreferrer">
        <img src="/vite.svg" class="logo" alt="Vite logo" />
      </a>
      <a href="https://vuejs.org/" target="_blank" rel="noopener noreferrer">
        <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
      </a>
    </div>
  </div>
  <div className="adhesive-container">
    <AdhesiveContainer
      position="top"
      bounding-el=".adhesive-container"
      class="my-classname"
      outer-class="my-outer-classname"
      inner-class="my-inner-classname"
      active-class="my-active-classname"
      released-class="my-released-classname"
    >
      Sticky Element
    </AdhesiveContainer>
    <a href="https://vite.dev" target="_blank" rel="noopener noreferrer">
      <img src="/vite.svg" class="logo" alt="Vite logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank" rel="noopener noreferrer">
      <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
    </a>
  </div>
  <h1>Vite + Vue</h1>
  <div class="card">
    <button type="button" @click="count++">count is {{ count }}</button>
    <p>
      Edit
      <code>src/App.vue</code> and save to test HMR
    </p>
  </div>
  <p class="read-the-docs">Click on the Vite and Vue logos to learn more</p>
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}

.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}

.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}

.read-the-docs {
  color: #888;
}
</style>
