// playground/vue/src/App.vue
<script setup lang="ts">
import { AdhesiveContainer, useAdhesive } from "@adhesivejs/vue";
import { ref, useTemplateRef } from "vue";
import type { AdhesivePosition } from "@adhesivejs/core";

const count = ref(0);
const position = ref<AdhesivePosition>("top");

const targetEl = useTemplateRef("target");
const boundingEl = useTemplateRef("bounding");

useAdhesive({ target: targetEl, bounding: boundingEl });
</script>

<template>
  <div>
    <div ref="bounding">
      <div ref="target">Sticky Element</div>
      <a href="https://vite.dev" target="_blank" rel="noopener noreferrer">
        <img src="/vite.svg" class="logo" alt="Vite logo" />
      </a>
      <a href="https://vuejs.org/" target="_blank" rel="noopener noreferrer">
        <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
      </a>
    </div>
  </div>
  <div className="adhesive-container">
    <AdhesiveContainer
      :position
      bounding-el=".adhesive-container"
      class="my-classname"
      outer-class="my-outer-classname"
      inner-class="my-inner-classname"
      active-class="my-active-classname"
      released-class="my-released-classname"
    >
      Sticky Element
    </AdhesiveContainer>
    <a href="https://vite.dev" target="_blank" rel="noopener noreferrer">
      <img src="/vite.svg" class="logo" alt="Vite logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank" rel="noopener noreferrer">
      <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
    </a>
  </div>
  <button type="button" @click="position = 'top'">
    Change Position to Top
  </button>
  <button type="button" @click="position = 'bottom'">
    Change Position to Bottom
  </button>
  <h1>Vite + Vue</h1>
  <div class="card">
    <button type="button" @click="count++">count is {{ count }}</button>
    <p>
      Edit
      <code>src/App.vue</code> and save to test HMR
    </p>
  </div>
  <p class="read-the-docs">Click on the Vite and Vue logos to learn more</p>
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}

.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}

.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}

.read-the-docs {
  color: #888;
}
</style>

// playground/react/src/App.tsx
import { AdhesiveContainer, useAdhesive } from "@adhesivejs/react";
import { useRef, useState } from "react";
import reactLogo from "./assets/react.svg";
import type { AdhesivePosition } from "@adhesivejs/core";
import "./App.css";
import viteLogo from "/vite.svg";

export function App() {
  const [count, setCount] = useState(0);
  const [position, setPosition] = useState<AdhesivePosition>("top");

  const targetEl = useRef<HTMLDivElement>(null);
  const boundingEl = useRef<HTMLDivElement>(null);

  useAdhesive({ target: targetEl, bounding: boundingEl });

  return (
    <div>
      <div ref={boundingEl}>
        <div ref={targetEl}>Sticky Element</div>
        <a href="https://vite.dev" target="_blank" rel="noopener noreferrer">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://react.dev" target="_blank" rel="noopener noreferrer">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <div className="adhesive-container">
        <AdhesiveContainer
          position={position}
          boundingEl=".adhesive-container"
          className="my-classname"
          outerClassName="my-outer-classname"
          innerClassName="my-inner-classname"
          activeClassName="my-active-classname"
          releasedClassName="my-released-classname"
        >
          Sticky Element
        </AdhesiveContainer>
        <a href="https://vite.dev" target="_blank" rel="noopener noreferrer">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://react.dev" target="_blank" rel="noopener noreferrer">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <button onClick={() => setPosition("top")}>Change Position to Top</button>
      <button onClick={() => setPosition("bottom")}>
        Change Position to Bottom
      </button>
      <h1>Vite + React</h1>
      <div className="card">
        <button onClick={() => setCount((count) => count + 1)}>
          count is {count}
        </button>
        <p>
          Edit <code>src/App.tsx</code> and save to test HMR
        </p>
      </div>
      <p className="read-the-docs">
        Click on the Vite and React logos to learn more
      </p>
    </div>
  );
}
